### ISSUE TITLE
Is the pre-release from the main branch?

### ISSUE THREAD

**Issue by petterhs** [t0tten/PinetimeApp#2]
Hi,

I can control music when using the apk from the pre-release but not when I'm building the project myself from the main branch. Is the release apk from another branch?

**Comment by roka** [comment]
Hi,

For spotify you need an API key, the key is currently not in the source code.
But in the built APK the key has been added.

You can generate a key from https://developer.spotify.com

**Comment by petterhs** [comment]
Aha! Thanks :)
